### ISSUE TITLE
scroll issue 

### ISSUE THREAD

**Issue by walaagomaa18** [edubarr/header-decor#46]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
           at android.view.ViewGroup.addViewInner(ViewGroup.java:1976)
           at android.view.ViewGroup.addView(ViewGroup.java:1871)
           at android.view.ViewGroup.addView(ViewGroup.java:1828)
           at android.view.ViewGroup.addView(ViewGroup.java:1808)

**Comment by starkej2** [comment]
Do you have steps to reproduce the issue @walaagomaa18?
